### PR TITLE
Custom references

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5)

### CODE REVIEW

**Review by RachelDuffin — CHANGES_REQUESTED** [review]
Suggestion re code style - maximum line lengths / spaces around operators and after commas and after comment hashes etc. Not anything to necessarily stop this merging, but you can set up checks for things like this in your IDE. This should also catch things in your readme for filemover.py, e.g. uncapitalised sentences / missing punctuation

Suggestion to use git flow naming convention when creating branches

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-:-NGbiQjp6WUeDnm8dQKc:b-e0nwt)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`custom_reference/file_mover.py` line 28 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbisnD30s-vv9lADx-:-NGbisnE83RrUxuAzXU5:b-w34f3v) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L28)):*
> ```Python
>         if folder and not os.path.exists(folder):
>             os.path.mkdir(folder)
>             #print("made r'%s'" % folder)
> ```

Remove print statement
___
*[`custom_reference/file_mover.py` line 62 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbj5dX7tU4dkUIRzlf:-NGbj5dX7tU4dkUIRzlg:b-w34f3v) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L62)):*
> ```Python
>             if re.match(r'(%s).*(.rhchp)' % (spec_number), file):
>                 found = True
>                 #print("found rhchp file already in output folder")
> ```

Remove print statement
___
*[`custom_reference/file_mover.py` line 125 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbjILZ2e6TSDWQ1kG3:-NGbjILZ2e6TSDWQ1kG4:b-w34f3v) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L125)):*
> ```Python
>                         if synd_chr==sample_chr and sample_start <synd_stop and sample_stop>synd_start and synd_type==sample_type:
>                             sample_skip=True
>                             #print(sample,call,syndrome)
> ```

Remove print statement

**Review by RachelDuffin — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

**Review by RachelDuffin — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5)* status: all files reviewed, 3 unresolved discussions (waiting on @RachelDuffin)

___
*[`custom_reference/file_mover.py` line 28 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbisnD30s-vv9lADx-:-NGpmXfC4XdOft9Q3-Xu:b-896fix) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L28)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Remove print statement
</blockquote></details>

Done.
___
*[`custom_reference/file_mover.py` line 62 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbj5dX7tU4dkUIRzlf:-NGpmYKC5mkhW1LM47Dr:b-896fix) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L62)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Remove print statement
</blockquote></details>

Done.
___
*[`custom_reference/file_mover.py` line 125 at r1](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5#-NGbjILZ2e6TSDWQ1kG3:-NGpmYx34qZVE__2KqUY:b-896fix) ([raw file](https://github.com/moka-guys/snp_array_transition_211220/blob/a5c6a9a0f67d4241e5222fbf98a2a02753010f22/custom_reference/file_mover.py#L125)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Remove print statement
</blockquote></details>

Done.

**Review by RachelDuffin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/snp_array_transition_211220/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
